### PR TITLE
Dummy file to be able to build on FreeBSD

### PR DESCRIPTION
**Pull request by slegrand45**
Hi,

Without this dummy "truststore_freebsd.go" file, i get these errors if i try a build on FreeBSD 14.3 / Go 1.21.13:
```
./cert.go:143:16: ca.installPlatform undefined (type *CA has no field or method installPlatform)
./cert.go:156:105: undefined: NSSBrowsers
./cert.go:157:13: undefined: CertutilInstallHelp
./cert.go:158:89: undefined: NSSBrowsers
./cert.go:160:126: undefined: NSSBrowsers
./cert.go:161:81: undefined: CertutilInstallHelp
./cert.go:172:102: undefined: NSSBrowsers
./cert.go:174:13: undefined: CertutilInstallHelp
./cert.go:175:157: undefined: NSSBrowsers
./cert.go:176:89: undefined: CertutilInstallHelp
./cert.go:176:89: too many errors
```

After adding this file, the build is ok and i am able to build [symfony-cli](https://github.com/symfony-cli/symfony-cli). So i can install API Platform as described here : [Getting Started With API Platform with Symfony](https://api-platform.com/docs/symfony/#using-symfony-cli)

I guess this is really a workaround but, at least, i'm now able to use `symfony-cli` on FreeBSD :slightly_smiling_face:

### CODE REVIEW

File: truststore_freebsd.go [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+import (
+	"os"
+)
+
+var (
+	FirefoxProfiles = []string{os.Getenv("HOME") + "/.mozilla/firefox/*",
+		os.Getenv("HOME") + "/.mozilla/firefox-trunk/*"}
+	NSSBrowsers = "Firefox and/or Chrome/Chromium"
+
+	CertutilInstallHelp string
```
Comment (tucksaun) [inline truststore_freebsd.go:16]: It's been a while since I used FreeBSD (and never as a desktop) but I think it has NSS support (at least I find it in FreshPorts). In such case we should try to mimic linux support and update this with the appropriate NSS install command.

File: truststore_freebsd.go [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+)
+
+func (ca *CA) installPlatform() error {
+	return nil
+}
```
Comment (tucksaun) [inline truststore_freebsd.go:21]: installing a custom certificate on FreeBSD seems to be done `/usr/local/etc/ssl/cert/` and then run `certctl rehash`

**Review by tucksaun — COMMENTED** [review]
thank you for initiating this.

FreeBSD and Linux support might be relatively close in term of support so we should be able to extract part of `truststore_linux.go` to `truststore_posix.go` and make truststore_posix built for linux and freebsd.
@fabpot WDYT?

File: truststore_freebsd.go (hunk 2 above)
Comment (slegrand45) [reply truststore_freebsd.go:21]: There is no `/usr/local/etc/ssl/cert/` on a FreeBSD default installation. But if you install the [`ca_root_nss` port](https://github.com/freebsd/freebsd-ports/tree/main/security/ca_root_nss), you get the following files:
```
/etc/ssl/cert.pem
/usr/local/etc/ssl/cert.pem.sample
/usr/local/openssl/cert.pem
/usr/local/share/certs/ca-root-nss.crt
/usr/local/share/licenses/ca_root_nss-3.108/LICENSE
/usr/local/share/licenses/ca_root_nss-3.108/MPL20
/usr/local/share/licenses/ca_root_nss-3.108/catalog.mk
```

File: truststore_freebsd.go (hunk 1 above)
Comment (slegrand45) [reply truststore_freebsd.go:16]: If it can help, the FreeBSD [NSS port](https://github.com/freebsd/freebsd-ports/tree/main/security/nss) installs all these files: [pkg-plist](https://github.com/freebsd/freebsd-ports/blob/main/security/nss/pkg-plist)

**Comment by tucksaun** [comment]
@slegrand45 thank you for the feedback. As NSS is not included by default I guess one could contribute its support on FreeBSD later on.

**Review by tucksaun — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
